### ISSUE TITLE
Leak detected by LSan

### ISSUE THREAD

**Issue by blino** [projectatomic/bubblewrap#270]
When bubblewrap is built with -fsanitize=address, a minor leak is detected by LSan/ASan:
```
==16045==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 27 byte(s) in 1 object(s) allocated from:
    #0 0x7f110f3bcb50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7f110ed6f61f in vasprintf (/lib/x86_64-linux-gnu/libc.so.6+0x8861f)

SUMMARY: AddressSanitizer: 27 byte(s) leaked in 1 allocation(s).
```
Running with LSAN_OPTIONS=report_objects=1 shows that it is the base_path variable ("/run/user/%d/.bubblewrap") in main().
It is declared with the cleanup_free attribute, but this cleanup is not run when in the parent process, calling monitor_child().

While this is a minor leak, it is a bit troubling when trying to debug leak in other programs run with bwrap, and built with -fsanitize=address.

A workaround could to explicitely free base_path variable as soon as we enter the parent block.
Other variables using the cleanup_free attribute in toplevel scope of main() likely have the same behavior: seccomp_data, args_data

**Comment by smcv** [comment]
Honestly, I would recommend not configuring bubblewrap with asan. Memory leak checkers seem unlikely to work particularly well in a program that forks but does not exec, but that's what bubblewrap has to do; and asan is [not safe for use in setuid programs](http://seclists.org/oss-sec/2016/q1/363) and [not designed for use in setuid programs](http://seclists.org/oss-sec/2016/q1/367), but bubblewrap is designed to be setuid root on at least some systems.

bubblewrap should be allocating a small, constant amount of memory (O(1) for any particular command-line), so any leaks are rather theoretical.

**Comment by smcv** [comment]
Changing `monitor_child` to return the exit status, and changing the call to it to do `return monitor_child(...)`, might be one way to make each forked process leave `main()` in a way that passes through the cleanup step without making bubblewrap unnecessarily complicated.

**Comment by blino** [comment]
Thanks, your suggestion allows to remove the LSan warning, see PR#271

My whole system is built using -fsanitize=address, that's why I experienced the issue, I did not explicitly want to diagnose leaks in bubblewrap.

**Comment by smcv** [comment]
> My whole system is built using -fsanitize=address

I would recommend not doing that (see oss-security links above).

**Comment by blino** [comment]
> I would recommend not doing that (see oss-security links above).

Right, thanks for the links.
My use case is about a specific test build, for an OS that targets embedded devices in the end.
